### ISSUE TITLE
fcitxで挿入モード抜けたときにIME OFFにならない

### ISSUE THREAD

**Issue by urihcim** [fuenor/im_control.vim#1]
fcitxにてIM_CtrlMode = 6で使用していますが、
挿入モードを抜けたときにIME OFFになりません。
2dd572a の前までは期待の動作(IME OFF)となっていました。

Vim 8.1.1635
fcitx 4.2.9.6
Arch Linux 5.2.2

**Comment by fuenor** [comment]
今回のコミットは機能的な追加を行ったわけではないのでとりあえずRevertしました。
ご面倒かけて申し訳ありません。

**Comment by urihcim** [comment]
ありがとうございます。
正常に動作するようになりました。
